//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_EF_WebGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int usuarioID { get; set; }
        public string usuarioNome { get; set; }
        public string usuarioEmail { get; set; }
        public string usuarioSenha { get; set; }
        public Nullable<bool> usuarioAtivo { get; set; }
    }
}
